##################################################################
/vis/open HepRepFile
#/vis/open DAWNFILE
#/vis/open HepRepXML
#/vis/open RayTracer
/vis/scene/create G2P.heprep
# just draw geometry:
/vis/drawVolume world
#####The following 3 lines = /vis/drawVolume world#######
#/vis/scene/create
#/vis/scene/add/volume
#/vis/sceneHandler/attach
#########################################################
#/vis/heprep/appendGeometry  True  ##this line is used for HepRepXML only
#/vis/viewer/set/culling global false  ##this cmd is used to remove invisable objs
# Specify view angle, good for online visulization only, not file
#/vis/viewer/set/viewpointThetaPhi 90. 0.
# Specify style (surface or wireframe):
/vis/viewer/set/style surface
/vis/heprep/setEventNumberSuffix -000

###The next line will invoke /tracking/storeTrajectory 1
/vis/scene/add/trajectories
/vis/scene/add/hits

# Draw coordinate axes: x,y,z axislength unit
/vis/scene/add/axes 0. 0. 0. 1.8 m

#/vis/modeling/trajectories/create/drawByParticleID True
#/vis/modeling/trajectories/drawByParticleID-0/set e- blue
#/vis/modeling/trajectories/drawByParticleID-0/set pr green
#/vis/modeling/trajectories/drawByParticleID-0/default/setDrawStepPts true
#/vis/modeling/trajectories/drawByParticleID-0/default/setStepPtsColour red
#/vis/modeling/trajectories/drawByParticleID-0/default/setStepPtsSize 2


#The next line can be executed only once, trajectory points are not shown by default
#/vis/modeling/trajectories/create/drawByCharge True
#modify current model to showing trajectory points and change color
#/vis/modeling/trajectories/drawByCharge-0/default/setDrawStepPts true
#/vis/modeling/trajectories/drawByCharge-0/default/setStepPtsColour red
#/vis/modeling/trajectories/drawByCharge-0/default/setStepPtsSize 2
##############################################
/run/verbose 0
/tracking/verbose 0
/mydet/verbose 0
#add your macro here, for example
#/tracking/particleOnly e-
#write out all tracks in txt output
#/tracking/particleOnly all
#/tracking/thisTrackOnly 4 
#set no txt output
/tracking/thisTrackOnly 0
/tracking/noSecondary 0
#################################################################
/run/beamOn 1
