/vis/viewer/set/lineSegmentsPerCircle 120

/vis/viewer/set/viewpointThetaPhi 30 120

/vis/viewer/set/cutawayMode intersection
/vis/viewer/addCutawayPlane 0 0 0  cm -1 0 0
#/vis/viewer/addCutawayPlane 0 0 0 cm 0 0 -1
#/vis/viewer/addCutawayPlane 3  0  0   cm -1 0 0
#/vis/viewer/addCutawayPlane 0   0 250  cm 0 0 -1
#/vis/viewer/addCutawayPlane 0   0 600  cm 0 0 1
#/vis/viewer/addCutawayPlane 0   0 600  cm 0 1 -1
#/vis/viewer/set/sectionPlane on 0 0 0  cm 0 -1 0
/run/beamOn 1
/vis/ogl/printEPS


